apiVersion: v1
kind: Pod
metadata:
  name: gpu-pod-03
  namespace: pai-gpu
spec:
    containers:
    - image: tensorflow:latest
      name: main
      resources:
        limits:
          cpu: 2
          memory: 1740Mi
        requests:
          cpu: 2
          memory: 1740Mi
